elasticsearch:
  url: localhost:9200

files:
  power: P1e-2024-3-19-2024-5-26.csv
  gas: P1g-2024-3-19-2024-5-26.csv

contract:
  fixed:
    power:
      t1: 0.22145
      t2: 0.20935
    gas: 0.99179

tax:
  power: 0.13165
  gas: 0.70544

easyEnergy:
  url: "https://mijn.easyenergy.com/nl/api/tariff"
  power: "getapxtariffs"
  gas: "getlebatariffs"
