spring:
  main:
    allow-bean-definition-overriding: true
  liquibase:
    url: jdbc:postgresql://localhost:${datasource.port}/${datasource.database}
    user: ${datasource.username}
    password: ${datasource.password}
    change-log: classpath:db/changelog.xml
  r2dbc:
    url: r2dbc:postgresql://localhost:${datasource.port}/${datasource.database}
    username: ${datasource.username}
    password: ${datasource.password}

datasource:
  host: localhost
  port: 5432
  username: user
  password: pass
  database: energy_simulator

elasticsearch:
  url: localhost:9200

files:
  power: P1e-2024-1-01-2024-5-01.csv
  gas: P1g-2024-1-01-2024-5-01.csv