elasticsearch:
  url: localhost:9200

files:
  power: P1e-2023-6-14-2024-6-12.csv
  gas: P1g-2023-6-14-2024-6-12.csv

contract:
  fixed:
    power:
      t1: 0.20929
      t2: 0.22145
    gas: 0.99235

tax:
  power: 0.13165
  gas: 0.70544

scop: 4.0

easyEnergy:
  url: "https://mijn.easyenergy.com/nl/api/tariff"
  power: "getapxtariffs"
  gas: "getlebatariffs"
