spring:
  liquibase:
    url: jdbc:postgresql://localhost:${datasource.port}/${datasource.database}
    user: ${datasource.username}
    password: ${datasource.password}
    change-log: classpath:db/changelog.xml
  r2dbc:
    url: r2dbc:postgresql://localhost:${datasource.port}/${datasource.database}
    username: ${datasource.username}
    password: ${datasource.password}

datasource:
  host: localhost
  port: 5432
  username: user
  password: pass
  database: energy_simulator

elasticsearch:
  url: localhost:9200

files:
  power: P1e-2024-1-01-2024-5-01.csv
  gas: P1g-2024-1-01-2024-5-01.csv

contract:
  type: fixed
  fixed:
    power:
      t1: 0.22145
      t2: 0.20935
    gas: 0.99179

easyEnergy:
  url: "https://mijn.easyenergy.com/nl/api/tariff"
  power: "getapxtariffs"
  gas: "getlebatariffs"
